// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SacideProject.Data.Concrete;

#nullable disable

namespace SacideProject.Data.Migrations
{
    [DbContext(typeof(SacideProjectContext))]
    [Migration("20230729063514_Mig1")]
    partial class Mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SacideProject.Entity.Danisman", b =>
                {
                    b.Property<int>("DanismanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanismanID"));

                    b.Property<string>("DanismanAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanismanSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TerapiID")
                        .HasColumnType("int");

                    b.HasKey("DanismanID");

                    b.HasIndex("TerapiID");

                    b.ToTable("Danismanlar");
                });

            modelBuilder.Entity("SacideProject.Entity.Terapi", b =>
                {
                    b.Property<int>("TerapiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerapiID"));

                    b.Property<string>("TerapiAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerapiSayisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TerapiID");

                    b.ToTable("Terapiler");
                });

            modelBuilder.Entity("SacideProject.Entity.Danisman", b =>
                {
                    b.HasOne("SacideProject.Entity.Terapi", "Terapi")
                        .WithMany("Danismanlar")
                        .HasForeignKey("TerapiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terapi");
                });

            modelBuilder.Entity("SacideProject.Entity.Terapi", b =>
                {
                    b.Navigation("Danismanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
